cloud:
  aws:
    region:
      static: ap-northeast-2

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    store-type: redis

springdoc:
  swagger-ui:
    enabled: true
    path: '/v1/api-docs.html'
    try-it-out-enabled: false
  version: 'v1'

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/bonheur;
    username: bonheur
    password: bo123

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        show_sql: true
  redis:
    host: localhost
    port: 6379
    password: 1234

apple:
  client_id: dummy-apple-client_id
  issuer: dummy-apple-issue

cloud:
  aws:
    s3:
      bucket: ${secret.aws.s3.bucket}
    stack:
      auto: false
    credentials:
      access-key: ${secret.aws.credentials.access}
      secret-key: ${secret.aws.credentials.secret}
---
spring:
  config:
    activate:
      on-profile: dev
  redis:
    host: ${secret.redis.host}
    port: ${secret.redis.port}
    password: ${secret.redis.password}
